#!/bin/bash

# Script to generate .env files for all services
# IP: 10.10.20.56

export IP_ADDRESS=${1:-10.10.20.56}

echo "Generating .env files for all services with IP: $IP_ADDRESS"

# Core Service
cat > services/unsia-core-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_core

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8001
LOG_LEVEL=info
EOF

# Reference Service
cat > services/unsia-reference-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_reference

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8002
LOG_LEVEL=info
EOF

# PMB Service
cat > services/unsia-pmb-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_pmb

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8003
LOG_LEVEL=info
EOF

# Academic Service
cat > services/unsia-academic-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_academic

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8004
LOG_LEVEL=info
EOF

# Finance Service
cat > services/unsia-finance-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_finance

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8005
LOG_LEVEL=info
EOF

# LMS Service
cat > services/unsia-lms-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_lms

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8006
LOG_LEVEL=info
EOF

# Assessment Service
cat > services/unsia-assessment-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_assessment

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8007
LOG_LEVEL=info
EOF

# HRIS Service
cat > services/unsia-hris-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_hris

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8008
LOG_LEVEL=info
EOF

# CRM Service
cat > services/unsia-crm-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_crm

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8009
LOG_LEVEL=info
EOF

# Portal Service
cat > services/unsia-portal-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_portal

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8010
LOG_LEVEL=info
EOF

echo "All .env files generated successfully!"
echo "All services configured to use IP: $IP_ADDRESS"
