#!/bin/bash

# Script to generate .env files for all services
# IP: 10.10.20.56

export IP_ADDRESS=${1:-10.10.20.56}

echo "Generating .env files for all services with IP: $IP_ADDRESS"

# ============================================
# Backend Services
# ============================================

# Core Service
cat > services/unsia-core-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_core

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8001
LOG_LEVEL=info
EOF

# Reference Service
cat > services/unsia-reference-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_reference

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8002
LOG_LEVEL=info
EOF

# PMB Service
cat > services/unsia-pmb-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_pmb

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8003
LOG_LEVEL=info
EOF

# Academic Service
cat > services/unsia-academic-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_academic

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8004
LOG_LEVEL=info
EOF

# Finance Service
cat > services/unsia-finance-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_finance

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8005
LOG_LEVEL=info
EOF

# LMS Service
cat > services/unsia-lms-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_lms

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8006
LOG_LEVEL=info
EOF

# Assessment Service
cat > services/unsia-assessment-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_assessment

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8007
LOG_LEVEL=info
EOF

# HRIS Service
cat > services/unsia-hris-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_hris

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8008
LOG_LEVEL=info
EOF

# CRM Service
cat > services/unsia-crm-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_crm

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8009
LOG_LEVEL=info
EOF

# Portal Service
cat > services/unsia-portal-service/.env << EOF
DATABASE_HOST=$IP_ADDRESS
DATABASE_PORT=5432
DATABASE_USER=unsia
DATABASE_PASSWORD=unsia123
DATABASE_NAME=unsia_portal

RABBITMQ_HOST=$IP_ADDRESS
RABBITMQ_PORT=5672
RABBITMQ_USER=guest
RABBITMQ_PASSWORD=guest

APP_HOST=0.0.0.0
APP_PORT=8010
LOG_LEVEL=info
EOF

# ============================================
# Frontend Services (PRODUCTION / REMOTE IP)
# ============================================

# Core Frontend
cat > frontend/unsia-core/.env << EOF
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_APP_NAME="UNSIA Core"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3001
NEXT_PUBLIC_PORT=3001
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# Reference Frontend
cat > frontend/unsia-reference/.env << EOF
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_APP_NAME="UNSIA Reference"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3002
NEXT_PUBLIC_PORT=3002
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# PMB Frontend
cat > frontend/unsia-pmb/.env << EOF
NEXT_PUBLIC_PMB_API=http://$IP_ADDRESS:8003
NEXT_PUBLIC_API_PMB_URL=http://$IP_ADDRESS:8003
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_APP_NAME="UNSIA PMB"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3003
NEXT_PUBLIC_PORT=3003
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
NEXT_PUBLIC_STORAGE_BUCKET=unsia-pmb-dev
NEXT_PUBLIC_STORAGE_REGION=ap-southeast-1
EOF

# Academic Frontend
cat > frontend/unsia-academic/.env << EOF
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_APP_NAME="UNSIA Academic"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3004
NEXT_PUBLIC_PORT=3004
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# Finance Frontend
cat > frontend/unsia-finance/.env << EOF
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_APP_NAME="UNSIA Finance"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3005
NEXT_PUBLIC_PORT=3005
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# LMS Frontend
cat > frontend/unsia-lms/.env << EOF
NEXT_PUBLIC_LMS_API=http://$IP_ADDRESS:8006
NEXT_PUBLIC_API_LMS_URL=http://$IP_ADDRESS:8006
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_APP_NAME="UNSIA LMS"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3006
NEXT_PUBLIC_PORT=3006
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# Assessment Frontend
cat > frontend/unsia-assessment/.env << EOF
NEXT_PUBLIC_ASSESSMENT_API=http://$IP_ADDRESS:8007
NEXT_PUBLIC_API_ASSESSMENT_URL=http://$IP_ADDRESS:8007
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_APP_NAME="UNSIA Assessment"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3007
NEXT_PUBLIC_PORT=3007
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# HRIS Frontend
cat > frontend/unsia-hris/.env << EOF
NEXT_PUBLIC_HRIS_API=http://$IP_ADDRESS:8008
NEXT_PUBLIC_API_HRIS_URL=http://$IP_ADDRESS:8008
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_APP_NAME="UNSIA HRIS"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3008
NEXT_PUBLIC_PORT=3008
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# CRM Frontend
cat > frontend/unsia-crm/.env << EOF
NEXT_PUBLIC_CRM_API=http://$IP_ADDRESS:8009
NEXT_PUBLIC_API_CRM_URL=http://$IP_ADDRESS:8009
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_PMB_API=http://$IP_ADDRESS:8003
NEXT_PUBLIC_API_PMB_URL=http://$IP_ADDRESS:8003
NEXT_PUBLIC_APP_NAME="UNSIA CRM"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3009
NEXT_PUBLIC_PORT=3009
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# Portal Web Frontend
cat > frontend/unsia-portal-web/.env << EOF
NEXT_PUBLIC_PORTAL_API=http://$IP_ADDRESS:8010
NEXT_PUBLIC_API_PORTAL_URL=http://$IP_ADDRESS:8010
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_PMB_API=http://$IP_ADDRESS:8003
NEXT_PUBLIC_API_PMB_URL=http://$IP_ADDRESS:8003
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_APP_NAME="UNSIA Portal"
NEXT_PUBLIC_APP_URL=http://$IP_ADDRESS:3010
NEXT_PUBLIC_PORT=3010
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_ANALYTICS=true
EOF

# ============================================
# Frontend Services (LOCAL DEVELOPMENT / HOST IP)
# ============================================

# Core Frontend (Port 3001)
cat > frontend/unsia-core/.env.local << EOF
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_APP_NAME="UNSIA Core"
NEXT_PUBLIC_APP_URL=http://localhost:3001
NEXT_PUBLIC_PORT=3001
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# Reference Frontend (Port 3002)
cat > frontend/unsia-reference/.env.local << EOF
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_APP_NAME="UNSIA Reference"
NEXT_PUBLIC_APP_URL=http://localhost:3002
NEXT_PUBLIC_PORT=3002
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# PMB Frontend (Port 3003)
cat > frontend/unsia-pmb/.env.local << EOF
NEXT_PUBLIC_PMB_API=http://$IP_ADDRESS:8003
NEXT_PUBLIC_API_PMB_URL=http://$IP_ADDRESS:8003
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_APP_NAME="UNSIA PMB"
NEXT_PUBLIC_APP_URL=http://localhost:3003
NEXT_PUBLIC_PORT=3003
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# Academic Frontend (Port 3004)
cat > frontend/unsia-academic/.env.local << EOF
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_APP_NAME="UNSIA Academic"
NEXT_PUBLIC_APP_URL=http://localhost:3004
NEXT_PUBLIC_PORT=3004
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# Finance Frontend (Port 3005)
cat > frontend/unsia-finance/.env.local << EOF
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_APP_NAME="UNSIA Finance"
NEXT_PUBLIC_APP_URL=http://localhost:3005
NEXT_PUBLIC_PORT=3005
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# LMS Frontend (Port 3006)
cat > frontend/unsia-lms/.env.local << EOF
NEXT_PUBLIC_LMS_API=http://$IP_ADDRESS:8006
NEXT_PUBLIC_API_LMS_URL=http://$IP_ADDRESS:8006
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_APP_NAME="UNSIA LMS"
NEXT_PUBLIC_APP_URL=http://localhost:3006
NEXT_PUBLIC_PORT=3006
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# Assessment Frontend (Port 3007)
cat > frontend/unsia-assessment/.env.local << EOF
NEXT_PUBLIC_ASSESSMENT_API=http://$IP_ADDRESS:8007
NEXT_PUBLIC_API_ASSESSMENT_URL=http://$IP_ADDRESS:8007
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_LMS_API=http://$IP_ADDRESS:8006
NEXT_PUBLIC_API_LMS_URL=http://$IP_ADDRESS:8006
NEXT_PUBLIC_APP_NAME="UNSIA Assessment"
NEXT_PUBLIC_APP_URL=http://localhost:3007
NEXT_PUBLIC_PORT=3007
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# HRIS Frontend (Port 3008)
cat > frontend/unsia-hris/.env.local << EOF
NEXT_PUBLIC_HRIS_API=http://$IP_ADDRESS:8008
NEXT_PUBLIC_API_HRIS_URL=http://$IP_ADDRESS:8008
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_APP_NAME="UNSIA HRIS"
NEXT_PUBLIC_APP_URL=http://localhost:3008
NEXT_PUBLIC_PORT=3008
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# CRM Frontend (Port 3009)
cat > frontend/unsia-crm/.env.local << EOF
NEXT_PUBLIC_CRM_API=http://$IP_ADDRESS:8009
NEXT_PUBLIC_API_CRM_URL=http://$IP_ADDRESS:8009
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_APP_NAME="UNSIA CRM"
NEXT_PUBLIC_APP_URL=http://localhost:3009
NEXT_PUBLIC_PORT=3009
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

# Portal Web Frontend (Port 3010)
cat > frontend/unsia-portal-web/.env.local << EOF
NEXT_PUBLIC_CORE_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_AUTH_API=http://$IP_ADDRESS:8001
NEXT_PUBLIC_API_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_CORE_URL=http://$IP_ADDRESS:8001
NEXT_PUBLIC_REFERENCE_API=http://$IP_ADDRESS:8002
NEXT_PUBLIC_API_REFERENCE_URL=http://$IP_ADDRESS:8002
NEXT_PUBLIC_PMB_API=http://$IP_ADDRESS:8003
NEXT_PUBLIC_API_PMB_URL=http://$IP_ADDRESS:8003
NEXT_PUBLIC_ACADEMIC_API=http://$IP_ADDRESS:8004
NEXT_PUBLIC_API_ACADEMIC_URL=http://$IP_ADDRESS:8004
NEXT_PUBLIC_FINANCE_API=http://$IP_ADDRESS:8005
NEXT_PUBLIC_API_FINANCE_URL=http://$IP_ADDRESS:8005
NEXT_PUBLIC_LMS_API=http://$IP_ADDRESS:8006
NEXT_PUBLIC_API_LMS_URL=http://$IP_ADDRESS:8006
NEXT_PUBLIC_ASSESSMENT_API=http://$IP_ADDRESS:8007
NEXT_PUBLIC_API_ASSESSMENT_URL=http://$IP_ADDRESS:8007
NEXT_PUBLIC_HRIS_API=http://$IP_ADDRESS:8008
NEXT_PUBLIC_API_HRIS_URL=http://$IP_ADDRESS:8008
NEXT_PUBLIC_CRM_API=http://$IP_ADDRESS:8009
NEXT_PUBLIC_API_CRM_URL=http://$IP_ADDRESS:8009
NEXT_PUBLIC_PORTAL_API=http://$IP_ADDRESS:8010
NEXT_PUBLIC_API_PORTAL_URL=http://$IP_ADDRESS:8010
NEXT_PUBLIC_APP_NAME="UNSIA Portal"
NEXT_PUBLIC_APP_URL=http://localhost:3010
NEXT_PUBLIC_PORT=3010
NEXT_PUBLIC_ENABLE_DEBUG=false
EOF

echo "All .env files generated successfully!"
echo "All services configured to use IP: $IP_ADDRESS"
echo "============================================"
echo ""
echo "Backend Services (Go):"
echo "  - Core Service:       http://$IP_ADDRESS:8001"
echo "  - Reference Service: http://$IP_ADDRESS:8002"
echo "  - PMB Service:      http://$IP_ADDRESS:8003"
echo "  - Academic Service: http://$IP_ADDRESS:8004"
echo "  - Finance Service:  http://$IP_ADDRESS:8005"
echo "  - LMS Service:      http://$IP_ADDRESS:8006"
echo "  - Assessment Svc:   http://$IP_ADDRESS:8007"
echo "  - HRIS Service:    http://$IP_ADDRESS:8008"
echo "  - CRM Service:      http://$IP_ADDRESS:8009"
echo "  - Portal Service:   http://$IP_ADDRESS:8010"
echo ""
echo "Frontend Services (Next.js):"
echo "  - Core Frontend:     http://$IP_ADDRESS:3001"
echo "  - Reference Front:   http://$IP_ADDRESS:3002"
echo "  - PMB Frontend:      http://$IP_ADDRESS:3003"
echo "  - Academic Frontend: http://$IP_ADDRESS:3004"
echo "  - Finance Frontend:  http://$IP_ADDRESS:3005"
echo "  - LMS Frontend:      http://$IP_ADDRESS:3006"
echo "  - Assessment Fe:     http://$IP_ADDRESS:3007"
echo "  - HRIS Frontend:     http://$IP_ADDRESS:3008"
echo "  - CRM Frontend:      http://$IP_ADDRESS:3009"
echo "  - Portal Web Fe:     http://$IP_ADDRESS:3010"
